#!/usr/bin/env bash
# shellcheck disable=SC2154
# Configure Nginx so that its HTTP response contains a custom header (on
# web-01 and web-02)

apt-get -y update
apt-get -y install nginx

redirect='\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}'

err='\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}'

header="X-Served-By"
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
echo "Hello World!" | sudo tee /var/www/html/index.html

sed -i "/server_name _;/ a \ $redirect" /etc/nginx/sites-available/default
sed -i "/server_name _;/ a \ $err" /etc/nginx/sites-enabled/default
sed -i "/http {/a\\\tadd_header $header $HOSTNAME;" /etc/nginx/nginx.conf
sudo /etc/init.d/nginx restart
