#!/usr/bin/env bash
# Bash script that displays I am invincible!!! when receiving a SIGTERM signal

trap "echo I am invincible!!!" SIGTERM

i=0

while [ $i -lt 5 ]
do
echo "To infinity and beyond"
sleep 2
done
